name: EusPrivChat
main: cc.eumc.PrivChat
version: 2.0.3
author: EucalyptusLeaves
api-version: 1.13
depend: [ProtocolLib]
commands:
  chatmode:
    aliases: ['cm']
    description: Command for PrivChat whose function is change chat mode
permissions:
  privchat.global:
    description: Allows a player to send global messages